# Generated by Django 6.0.2 on 2026-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(max_length=20, unique=True, verbose_name="Ticker"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Ação"),
                            ("FII", "FII"),
                            ("ETF", "ETF"),
                            ("INTERNATIONAL", "Stock Internacional"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("BRL", "Real (BRL)"), ("USD", "Dólar (USD)")],
                        default="BRL",
                        max_length=3,
                        verbose_name="Moeda",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["ticker"],
            },
        ),
    ]
